import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "#ECF4FE",
    marginTop: 18,
    padding: 5,
    flexDirection: "column",
  },
  iglogo: {
    width: 60,
    alignSelf: "center",
    resizeMode: "contain",
    justifyContent: "flex-start",
  },
  text: {
    marginTop: 10,
    alignSelf: "center",
    color: "#77838F",
    fontWeight: "500",
    fontSize: 16,
  },
  textinput: {
    borderStyle: "solid",
    borderColor: "grey",
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderRadius: 10,
    padding: 7,
    backgroundColor: "white",
    marginLeft: 10,
    marginRight: 10,
    marginBottom: 10,
  },
  metalogo: {
    height: 10,
    margin: 10,
    width: "100%",
    alignSelf: "center",
    resizeMode: "contain",
  },
  buttonEntrar: {
    borderStyle: "solid",
    borderColor: "grey",
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderRadius: 20,
    padding: 7,
    backgroundColor: "#0064E0",
    marginLeft: 10,
    marginRight: 10,
    marginBottom: 10,
    alignItems: "center",
  },
  buttonCriar: {
    borderStyle: "solid",
    borderColor: "grey",
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderRadius: 20,
    padding: 7,
    backgroundColor: "#ECF4FE",
    marginLeft: 10,
    marginRight: 10,
    marginBottom: 10,
    alignItems: "center",
  },
});
